project:
  type: website
  output-dir: _site

date: last-modified
date-format: D MMMM, YYYY

website:
  title: "SETAC 2025: Introduction to Reproducibility with R"
  
  page-footer:
    left: "Rand E (2025). SETAC 2025: Introduction to Reproducibility with R. <https://3mmarand.github.io/setac-13-intro-to-r/>."
    right:
      - icon: github
        href: https://github.com/3mmaRand/setac-13-intro-to-r
        text: "Emma on GitHub"  
  navbar:
    background: light
    twitter-card: true
    site-url: https://3mmarand.github.io/setac-13-intro-to-r/
    repo-url: https://github.com/3mmaRand/setac-13-intro-to-r
    issue-url: https://github.com/3mmaRand/setac-13-intro-to-r/issues/new/choose
    repo-actions: [edit, issue]
    page-navigation: true
    search: true
    left:
      - text: "Welcome!"
        file: index.qmd
      - text: "Prerequisites"
        file:  prerequisites.qmd
      - text: "Schedule and materials"
        file:  schedule.qmd
    tools:
    right:
      - icon: github
        href: https://github.com/3mmaRand/setac-13-intro-to-r
        text: "Emma on GitHub"

execute:
  echo: true
  warning: false
  output: true
  error: true
  collapse: true
  freeze: auto

engine: knitr

format:
  html:
    css: styles.css
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/3mmarand\.github\.io\/setac-13-intro-to-r'
    theme:
      light: [cosmo]
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-line-numbers: false
    toc: true
    toc-depth: 4
    fig-format: svg
    lightbox: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    
    author-meta: Emma Rand

metadata-files:
  - _downlit.yml

fig-dpi: 600

bibliography: references.bib

editor: source